sort_map = dict()
b_map = dict()
c_map = dict()

b_map['ns'] = 'ID'  # 新编板块代码
b_map['jzf'] = 'averageChange'  # 均涨幅
b_map['n'] = 'name'  # 板块名称
b_map['ns'] = 'ID'  # 新编板块代码
b_map['jzf'] = 'averageChange'  # 均涨幅
b_map['n'] = 'name'  # 板块名称
b_map['zcje'] = 'amount'  # 总成交额
b_map['zdjs'] = 'advanceAndDeclineCount'  # 涨跌家数
b_map['hsl'] = 'turnoverRate'  # 换手率
b_map['qzf'] = 'weightedChange'  # 权涨幅
b_map['lzg'] = 'stockID'  # 领涨股代码
b_map['lzgn'] = 'stockName'  # 领涨股名称
b_map['ggzf'] = 'stockChange'  # 个股涨幅
b_map['ggzfb'] = 'stockChangeRate'  # 个股涨幅比
b_map['lzgj'] = 'stockLastPrice'  # 领涨股最新价
b_map['zlzjjlr'] = 'netCapitalInflow'  # 主力净流入
b_map['ssbk'] = 'type'  # 板块类型
b_map['zlzjlr'] = 'capitalInflow'  # 主力资金流入
b_map['zlzjlc'] = 'capitalOutflow'  # 主力资金流出
b_map['zlzjjlr5'] = 'netCapitalInflow5'  # 5日主力资金净流入
b_map['zlzjjlr10'] = 'netCapitalInflow10'  # 10日主力资金净流入
b_map['hot'] = 'hot'  # 优品热度值
b_map['xcjl'] = 'nowVolume'  # 现手
b_map['zcjl'] = 'volume'  # 总手
b_map['ztjs'] = 'limitUpCount'  # 涨停家数
b_map['dtjs'] = 'limitDownCount'  # 跌停家数
b_map['zxj'] = 'lastPrice'  # 板块指数最新价
b_map['zdf'] = 'changeRate'  # 板块指数涨跌幅
b_map['zdf5'] = 'changeRate5'  # 板块指数5日涨跌幅
b_map['zdf10'] = 'changeRate10'  # 板块指数10日涨跌幅
b_map['lzzh'] = 'flowValue'  # 流值总和
b_map['szzh'] = 'totalValue'  # 市值总和
b_map['kpj'] = 'openPrice'  # 开盘板块指数
b_map['zgj'] = 'highPrice'  # 最高板块指数
b_map['zdj'] = 'lowPrice'  # 最低板块指数
b_map['wb'] = 'orderRatio'  # 委比
b_map['wc'] = 'entrustDiff'  # 委差
b_map['wm3'] = 'entrustBuyVolume'  # 委买
b_map['wm4'] = 'entrustSellVolume'  # 委卖
b_map['dtsyl'] = 'PE'  # 动态市盈率
b_map['jtsyl'] = 'SPE'  # 静态市盈率
b_map['sjl'] = 'ROE'  # 市净率
b_map['zsj'] = 'preClosePrice'  # 前收盘指数
b_map['zde'] = 'change'  # 涨跌额
b_map['zgb'] = 'riseRate'  # 涨股比
b_map['zf'] = 'amplitudeRate'  # 振幅

# 沪深港、新三板排序栏位
c_map['0'] = 'status'  # 交易状态
c_map['1'] = 'id'  # 代码
c_map['2'] = 'name'  # 名称
c_map['7'] = 'lastPrice'  # 最新价
c_map['8'] = 'highPrice'  # 最高价
c_map['9'] = 'lowPrice'  # 最低价
c_map['10'] = 'openPrice'  # 今开价
c_map['11'] = 'preClosePrice'  # 昨收价
c_map['12'] = 'changeRate'  # 涨跌比率
c_map['13'] = 'volume'  # 总手
c_map['14'] = 'nowVolume'  # 当前成交量
c_map['15'] = 'turnoverRate'  # 换手率
c_map['19'] = 'change'  # 涨跌
c_map['20'] = 'amount'  # 成交金额
c_map['21'] = 'volumeRatio'  # 量比
c_map['24'] = 'buyVolume'  # 外盘量
c_map['25'] = 'sellVolume'  # 内盘量
c_map['26'] = 'totalValue'  # 总市值
c_map['27'] = 'flowValue'  # 流通市值
c_map['28'] = 'netAsset'  # 净资产
c_map['29'] = 'pe'  # 动态市盈率
c_map['30'] = 'pb'  # 市净率
c_map['31'] = 'capitalization'  # 总股本
c_map['32'] = 'circulatingShares'  # 流通股
c_map['37'] = 'amplitudeRate'  # 振幅比率
c_map['38'] = 'receipts'  # 每股收益
c_map['42'] = 'pe2'  # 静态市盈率
c_map['53'] = 'orderRatio'  # 委比
c_map['86'] = 'monthChangeRate'  # 本月涨跌幅
c_map['87'] = 'yearChangeRate'  # 本年涨跌幅
c_map['88'] = 'recentMonthChangeRate'  # 近一月涨跌幅
c_map['89'] = 'recentYearChangeRate'  # 近一年涨跌幅

# 科创板特有排序栏位
c_map['72'] = 'afterHoursVolume'  # 盘后成交量
c_map['73'] = 'afterHoursAmount'  # 盘后成交额
# 期货特有排序栏位
c_map['500'] = 'averageValue'  # 均价
c_map['501'] = 'tradingDay'  # 交易日
c_map['502'] = 'settlementGroupID'  # 结算组代码
c_map['503'] = 'settlementID'  # 结算编号
c_map['504'] = 'preSettlement'  # 昨结算价
c_map['505'] = 'preInterest'  # 昨持仓量（无小数点）
c_map['506'] = 'openInterest'  # 持仓量（0位小数）
c_map['507'] = 'position_chg'  # 日增（0位小数）
c_map['508'] = 'close'  # 今收盘价
c_map['509'] = 'settlement'  # 今结算价
c_map['510'] = 'preDelta'  # 昨虚实度
c_map['511'] = 'currDelta'  # 今虚实度
c_map['512'] = 'updateMillisec'  # 最后修改毫秒
c_map['513'] = 'limitUp'  # 涨停价
c_map['514'] = 'limitDown'  # 跌停价
c_map['515'] = 'buyPrice'  # 买一价
c_map['516'] = 'sellPrice'  # 卖一价
c_map['517'] = 'underlyingLastPx'  # 标的现价（两位小数）
c_map['518'] = 'underlyingPreClose'  # 标的昨收（两位小数）
c_map['519'] = 'underlyingchg'  # 标的涨跌（两位小数）
c_map['520'] = 'underlyingSymbol'  # 标的名称
c_map['521'] = 'change1'  # 涨跌1
c_map['522'] = 'posDiff'  # 仓差
c_map['523'] = 'totalBid'  # 委买
c_map['524'] = 'totalAsk'  # 委卖
c_map['525'] = 'entrustDiff'  # 委差
c_map['526'] = 'intersectionNum'  # 交割点数
c_map['527'] = 'exePrice'  # 行权价
c_map['528'] = 'premiumRate'  # 溢价率BANKUAISORTING_1
c_map['529'] = 'remainDate'  # 剩余天数
c_map['530'] = 'leverageRatio'  # 杠杆比率
c_map['531'] = 'impliedVolatility'  # 隐含波动率
c_map['532'] = 'delta,gramma,theta,rho,vega'  # 无风险利率
# 沪深港增值指标排序栏位
c_map['-19'] = 'ultraLargeNetInflow'  # 超大单净流入
c_map['-20'] = 'largeNetInflow'  # 大单净流入
c_map['-21'] = 'mediumNetInflow'  # 中单净流入
c_map['-22'] = 'smallNetInflow'  # 小单净流入
c_map['-34'] = 'BBD'  # 大单净差
c_map['-35'] = 'BBD5'  # 五日大单净差
c_map['-36'] = 'BBD10'  # 十日大单净差
c_map['-37'] = 'DDX'  # 主力动向
c_map['-38'] = 'DDX5'  # 五日主力动向
c_map['-39'] = 'DDX10'  # 十日主力动向
c_map['-40'] = 'DDY'  # 涨跌动因
c_map['-41'] = 'DDY5'  # 五日涨跌动因
c_map['-42'] = 'DDY10'  # 十日涨跌动因
c_map['-47'] = 'netCapitalInflow'  # 主力净流入
c_map['-48'] = 'fiveMinutesChangeRate'  # 五分钟涨跌幅
c_map['-58'] = 'mainforceMoneyNetInflow5'  # 5日主力资金净流入
c_map['-59'] = 'mainforceMoneyNetInflow10'  # 10日主力资金净流入
c_map['-60'] = 'mainforceMoneyNetInflow20'  # 20日主力资金净流入
c_map['-61'] = 'ratioMainforceMoneyNetInflow5'  # 5日主力资金净流入占比
c_map['-62'] = 'ratioMainforceMoneyNetInflow10'  # 10日主力资金净流入占比
c_map['-63'] = 'ratioMainforceMoneyNetInflow20'  # 20日主力资金净流入占比

sort_map['BANKUAI'] = ['BANKUAISORTING_1', 'BANKUAISORTING_2']
sort_map['CATE'] = ['CATESORTING_1', 'CATESORTING_2', 'CATESORTING_3', 'CATESORTING_4']

sort_map['SORT_TESTCASEIDS'] = sort_map['BANKUAI'] + sort_map['CATE']

sort_map['BANKUAISORTING_1'] = b_map
sort_map['BANKUAISORTING_2'] = b_map
sort_map['CATESORTING_1'] = c_map
sort_map['CATESORTING_2'] = c_map
sort_map['CATESORTING_3'] = c_map
sort_map['CATESORTING_4'] = c_map
